baseURL = "/"
languageCode = "en-us"
title = "Asim Ihsan's Meanderings"

[permalinks]
    posts = "/:filename/"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 1

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 2

    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 3
    
#    [[menu.main]]
#        name = "Projects"
#        url = "/projects/"
#        weight = 3

[params]
    backgroundColor = "#FCFCFC"
    textColor = "#000000"
    homeText = """
Hi, I'm Asim. I work as a software engineer.
"""
    recaptchaV2SiteKey = "6LcGPMIZAAAAAPnC_pt8UFNBWN2n8MBB_zyIidBS"

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2

  [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokailight"
        tabWidth = 4

[outputs]
    page = ["HTML", "JSON"]
