graph TD
  A[Site Key] --> C[NaCL Secretbox Encryption 1]
  B[Plaintext] --> C[NaCL Secretbox Encryption 1]
  D[Nonce 1] --> C[NaCL Secretbox Encryption 1]
  C[NaCL Secretbox Encryption 1] --> E[Ciphertext 1]

  A[Site Key] --> F[NaCL Secretbox Encryption 2]
  B[Plaintext] --> F[NaCL Secretbox Encryption 2]
  G[Nonce 2] --> F[NaCL Secretbox Encryption 2]
  F[NaCL Secretbox Encryption 2] --> H[Ciphertext 2]
