graph TD
  subgraph site key
    A[Site Key]
  end
  subgraph generate key
    A --> D[HKDF Function - Key]
    J("Input: key") --> D[HKDF Function - Key]
    D[HKDF Function - Key] --> E[Generated Secret Key]
  end

  subgraph plaintext
    F[Plaintext]
  end

  subgraph generate nonce
    A[Site Key] --> B[HKDF Function - Nonce]
    F --> B
    I("Input: nonce") --> B[HKDF Function - Nonce]
    B[HKDF Function - Nonce] --> C[Generated Nonce]
  end

  subgraph first encryption
    E[Generated Secret Key] --> G[NaCL Secretbox Encryption 1]
    F --> G[NaCL Secretbox Encryption 1]
    C[Generated Nonce] --> G[NaCL Secretbox Encryption 1]
    G[NaCL Secretbox Encryption 1] --> H[Ciphertext 1]
  end

  subgraph second encryption
    E[Generated Secret Key] --> K[NaCL Secretbox Encryption 2]
    F --> K[NaCL Secretbox Encryption 2]
    C[Generated Nonce] --> K[NaCL Secretbox Encryption 2]
    K[NaCL Secretbox Encryption 2] -->L["Ciphertext 2 (same as 1)"]
  end
