#!/usr/bin/env bash

set -euxo pipefail

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rm -rf "$SCRIPT_DIR"/../hugo/build
(cd "$SCRIPT_DIR"/../hugo && \
    HUGO_ENV=production HUGO_BASEURL='https://preprod-asim.ihsan.io' hugo --destination build)

# (cd "$SCRIPT_DIR"/../hugo/build && \
#     fd . -e html . | xargs -P 1 -I{} bash -c \
#         'echo {} && cat {} | critical --inline | sponge {}'
# )

"$SCRIPT_DIR"/../src/compress_build.py

rm -rf cdk/cdk.out
(cd cdk && cdk deploy --require-approval never 'preprod-AsimIhsanIoCdkStack')

"$SCRIPT_DIR"/../src/s3-cf-upload-invalidate-staging
