#!/usr/bin/env bash

set -euxo pipefail

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
ROOT_DIR=$(cd -- "$SCRIPT_DIR"/.. && pwd)

rm -rf "${ROOT_DIR}"/hugo/build
(cd "${ROOT_DIR}"/hugo && \
    HUGO_ENV=production HUGO_BASEURL='https://preprod-asim.ihsan.io' hugo --destination build)

# (cd "$SCRIPT_DIR"/../hugo/build && \
#     fd . -e html . | xargs -P 1 -I{} bash -c \
#         'echo {} && cat {} | critical --inline | sponge {}'
# )

rm -rf cdk/cdk.out
(cd cdk && cdk deploy --require-approval never 'preprod-AsimIhsanIoCdkStack')

"${ROOT_DIR}"/src/s3-cf-upload-invalidate-staging
